### ISSUE TITLE
Support for creating VPN providers

### ISSUE THREAD

**Issue by Astaoth** [jgke/connman-gtk#16] opened 2015-11-23 15:52 UTC
Hi,

Can you support OpenVPN connection from the UI ? And other VPN supported by connman ?

**Comment by jgke** [comment] 2015-11-23 15:59
Every VPN supported by ConnMan should be supported. OpenConnect support has some extra code on top since the cm's end is really bad on it, but the others should be working right now. I'm unsure what exactly are you asking here, or is this a bug report?

**Comment by Astaoth** [comment] 2015-11-23 16:03
Euh .. how can we add a vpn from connman-gtk ?

**Comment by jgke** [comment] 2015-11-23 16:07
VPNs must be added manually by editing files in /var/lib/connman-vpn for now. ConnMan has some support for creating them, I'll check it out in a couple of days that does it actually work.

**Comment by Astaoth** [comment] 2015-11-23 16:11
Well my question is to be able to add a new vpn from connman-gtk with an UI instead of writing a config file in /var/lib/connman-vpn.

**Comment by jgke** [comment] 2015-11-23 16:16
Oh, and this is actually a duplicate of #5, I reworded the title there now.

**Closed by jgke** 2015-11-23 16:16 UTC
Labels: enhancement
